import './globals.css'
import { Inter } from 'next/font/google'
import React from 'react'
import NavBar from '@/pages/navBar/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Ft_transcendence',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
