ARG POSTGRES_USER
ARG POSTGRES_HOST

FROM node:20-alpine3.17

RUN apk --update add postgresql-client

WORKDIR /usr/src/app


COPY package*.json ./

RUN npm install

COPY . .


RUN chmod +x init.sh


EXPOSE 3001

ENTRYPOINT ["sh", "/usr/src/app/init.sh"]

CMD ["npm", "run", "start:dev"]
